# Generated by Django 3.2.13 on 2022-05-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # TODO::
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('brand_logo_image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_exclusive', models.BooleanField(db_index=True, default=False)),
                ('is_recognised_brand', models.BooleanField(db_index=True, default=False)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'db_table': 'brands',
            },
        ),
    ]
