# Generated by Django 3.2.13 on 2022-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(db_index=True, max_length=255, verbose_name='Filename')),
                ('storage_id', models.CharField(blank=True, db_index=True, max_length=255, null=True,
                                                verbose_name='Storage Bucket Key')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternate Text')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Size')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Image',
                'db_table': 'image_mst',
            },
        ),
    ]
