# Generated by Django 3.2.13 on 2022-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('qb_id',
                 models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='QuickBook ID')),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Company Name')),
                ('address', models.CharField(max_length=255, verbose_name='Street')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zip_pin_code', models.CharField(max_length=15, verbose_name='Zipcode')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'db_table': 'vendor_mst',
            },
        ),
    ]
