# Generated by Django 3.2.13 on 2022-05-29 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_catalog', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True,
                                          help_text='Note: e.g Bengali, Gujarati, Kashmiri, Luchnowi, Maharashtrian.',
                                          max_length=255, verbose_name='Name')),
                ('description',
                 models.TextField(blank=True, help_text='Note: e.g describe the about the region.', max_length=300,
                                  null=True, verbose_name='Description')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, db_index=True, default=1,
                                                                   help_text='Note: Define the display order of region in consumer phasing application.',
                                                                   null=True, verbose_name='Display Order')),
                ('is_approved',
                 models.BooleanField(db_index=True, default=False, help_text='Note: Mark the Region as approved.',
                                     verbose_name='Is Approved?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='product_catalog.image')),
            ],
            options={
                'verbose_name': 'Region',
                'db_table': 'region_mst',
            },
        ),
    ]
