# Generated by Django 3.2.13 on 2022-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0005_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qb_id',
            field=models.CharField(blank=True, db_index=True, help_text='Note: Quickbook vendor linking ID.', max_length=30, null=True, verbose_name='Quickbook ID'),
        ),
    ]
