# Generated by Django 3.2.13 on 2022-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_catalog', '0005_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Note: Mark the brand as approved.',
                                      verbose_name='Is Approved ?'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_exclusive',
            field=models.BooleanField(db_index=True, default=False, help_text='Note: Mark the brand as exclusive.',
                                      verbose_name='Is Exclusive ?'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_recognised_brand',
            field=models.BooleanField(db_index=True, default=False, help_text='Note: Mark the brand as recognised.',
                                      verbose_name='Is Recognised Brand ?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, help_text='Note: e.g 20 - 20 Nice', max_length=255, unique=True,
                                   verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_index=True,
                                   help_text='Note: e.g Bengali, Gujarati, Kashmiri, Luchnowi, Maharashtrian.',
                                   max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qb_id',
            field=models.CharField(blank=True, db_index=True, help_text='Note: Quickbook vendor linking ID.',
                                   max_length=30, null=True, verbose_name='Quickbook ID'),
        ),
    ]
