# Generated by Django 3.2.13 on 2022-05-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('storage_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Image',
                'db_table': 'images',
            },
        ),
    ]
