# Generated by Django 3.2.13 on 2022-05-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0006_auto_20220529_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBrand',
            fields=[
                ('vendor_brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.brand', verbose_name='Brand Name')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.vendor', verbose_name='Vendor Name')),
            ],
            options={
                'verbose_name': 'Vendor Brand',
                'db_table': 'vendor_brand_link',
                'unique_together': {('vendor_brand_id', 'vendor', 'brand')},
            },
        ),
    ]
