# Generated by Django 3.2.13 on 2022-05-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0006_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('region_description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.image')),
            ],
            options={
                'verbose_name': 'Region',
                'db_table': 'regions',
            },
        ),
    ]
