# Generated by Django 3.2.13 on 2022-05-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0007_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_index=True, max_length=255)),
                ('item_alternate_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'items',
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_logo_image_id',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.image'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qb_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
