# Generated by Django 3.2.13 on 2022-05-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0008_auto_20220529_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Note: e.g Indian, Pakistani, Bangladeshi.', max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Note: e.g describe the about the cuisine.', max_length=300, null=True, verbose_name='Description')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, help_text='Note: Define the display order of region in consumer phasing application.', null=True, verbose_name='Display Order')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Note: Mark the cuisine as approved.', verbose_name='Is Approved?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.image')),
            ],
            options={
                'verbose_name': 'Cuisine',
                'db_table': 'cuisine_mst',
            },
        ),
    ]
