# Generated by Django 3.2.13 on 2022-05-29 16:46

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0010_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, help_text='Note: Define the display order of the category to consumer application.', null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, help_text='Note: Define the display order of the cuisine to consumer application.', null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='region',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, help_text='Note: Define the display order of the region to consumer application.', null=True, verbose_name='Display Order'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Sub Category Name')),
                ('description', models.TextField(blank=True, help_text='Note: e.g describe about the sub category.', max_length=300, null=True, verbose_name='Description')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, help_text='Note: Define the display order of the sub category for consumer application.', null=True, verbose_name='Display Order')),
                ('background_hex_code', colorfield.fields.ColorField(db_index=True, default=False, image_field=None, max_length=18, samples=None, verbose_name='Background Color')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Note: Mark the sub category as approved.', verbose_name='Is Approved ?')),
                ('is_tax_applicable', models.BooleanField(db_index=True, default=False, help_text='Note: Mark the sub category as taxable.', verbose_name='Is Tax Applicable ?')),
                ('effective_start_date', models.DateField(blank=True, db_index=True, help_text='Note: This sub category will be only be shown starting this date.', null=True, verbose_name='Effective Start Date')),
                ('effective_end_date', models.DateField(blank=True, db_index=True, help_text='Note: This sub category will not be shown after this date.', null=True, verbose_name='Effective End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.image')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'sub_category_mst',
            },
        ),
    ]
