# Generated by Django 3.2.13 on 2022-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0011_auto_20220529_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='effective_end_date',
            field=models.DateField(blank=True, db_index=True, help_text='Note: This sub category will not be shown after this date.', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='effective_start_date',
            field=models.DateField(blank=True, db_index=True, help_text='Note: This sub category will be only be shown starting this date.', null=True, verbose_name='Start Date'),
        ),
    ]
