# Generated by Django 3.2.13 on 2022-05-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0012_auto_20220529_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubCategory',
            fields=[
                ('category_sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.category', verbose_name='Category Name')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.subcategory', verbose_name='Sub Category Name')),
            ],
            options={
                'verbose_name': 'Category Sub Category',
                'db_table': 'category_sub_category_link',
                'unique_together': {('category_sub_category_id', 'category', 'sub_category')},
            },
        ),
    ]
