# Generated by Django 3.2.13 on 2022-05-29 17:45

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0014_auto_20220529_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysubcategory',
            options={'verbose_name': ''},
        ),
        migrations.AlterModelOptions(
            name='vendorbrand',
            options={'verbose_name': ''},
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Note: Mark the brand as approved.', verbose_name='Is Approved?'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_exclusive',
            field=models.BooleanField(db_index=True, default=False, help_text='Note: Mark the brand as exclusive.', verbose_name='Is Exclusive?'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_recognised_brand',
            field=models.BooleanField(db_index=True, default=False, help_text='Note: Mark the brand as recognised.', verbose_name='Is Recognised Brand?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='background_hex_code',
            field=colorfield.fields.ColorField(db_index=True, default=False, image_field=None, max_length=18, samples=None, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description (Optional)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Approved?'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='background_hex_code',
            field=colorfield.fields.ColorField(db_index=True, default=False, image_field=None, max_length=18, samples=None, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='categories',
            field=models.ManyToManyField(db_index=True, through='product_catalog.CategorySubCategory', to='product_catalog.Category', verbose_name='Select category this belongs to?'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description (optional)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Approved?'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_tax_applicable',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Tax Applicable?'),
        ),
    ]
