# Generated by Django 3.2.13 on 2022-05-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0015_auto_20220529_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionCuisine',
            fields=[
                ('region_cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.cuisine', verbose_name='Cuisine Name')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.region', verbose_name='Region Name')),
            ],
            options={
                'verbose_name': '',
                'db_table': 'region_cuisine_id',
                'unique_together': {('region_cuisine_id', 'region', 'cuisine')},
            },
        ),
        migrations.AddField(
            model_name='cuisine',
            name='regions',
            field=models.ManyToManyField(db_index=True, through='product_catalog.RegionCuisine', to='product_catalog.Region'),
        ),
        migrations.AddField(
            model_name='region',
            name='cuisines',
            field=models.ManyToManyField(db_index=True, through='product_catalog.RegionCuisine', to='product_catalog.Cuisine'),
        ),
    ]
