# Generated by Django 3.2.13 on 2022-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0017_alter_vendor_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
