# Generated by Django 3.2.13 on 2022-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode',
                 models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Zipcode')),
                ('city', models.CharField(db_index=True, max_length=120, verbose_name='City')),
                ('state', models.CharField(db_index=True, max_length=120, verbose_name='State')),
                ('lat', models.DecimalField(db_index=True, decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('long', models.DecimalField(db_index=True, decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('country', models.CharField(db_index=True, default='USA', max_length=120, verbose_name='Country')),
                ('zipcode_type', models.CharField(max_length=30, verbose_name='Zipcode Type')),
                ('is_decommisioned', models.BooleanField(default=False, verbose_name='Is Decommisioned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zipcode',
                'db_table': 'zipcode_mst',
            },
        ),
    ]
