# Generated by Django 3.2.13 on 2022-05-29 05:31

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    schema_editor.execute("ALTER SEQUENCE tax_mst_tax_rate_id_seq RESTART WITH 20000;")


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('system_management', '0002_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_rate',
                 models.DecimalField(db_index=True, decimal_places=6, max_digits=9, verbose_name='State Tax Rate')),
                ('county_rate',
                 models.DecimalField(db_index=True, decimal_places=6, max_digits=9, verbose_name='County Tax Rate')),
                ('special_rate',
                 models.DecimalField(db_index=True, decimal_places=6, max_digits=9, verbose_name='Special Rate')),
                ('combined_district_rate', models.DecimalField(db_index=True, decimal_places=6, max_digits=9,
                                                               verbose_name='Combined District Tax Rate')),
                ('is_freight_taxable', models.BooleanField(default=False, verbose_name='Is Freight Taxable?')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zipcode',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system_management.zipcode',
                                      verbose_name='Zipcode')),
            ],
            options={
                'verbose_name': 'Tax',
                'db_table': 'tax_mst',
            },
        ),
        migrations.RunPython(forward, backward, atomic=True)
    ]
