# Generated by Django 3.2.13 on 2022-05-29 05:53

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_management', '0006_notificationoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_additional_text',
            field=models.CharField(help_text='Note: e.g Email Notification, Push Notification, Text Notification',
                                   max_length=255, verbose_name='Notification Channel Description'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_channel',
            field=models.CharField(choices=[('Email', 'EMAIL'), ('Push', 'PUSH'), ('Sms', 'SMS')], db_index=True,
                                   help_text='Note: e.g Email, Sms, Push', max_length=30,
                                   verbose_name='Notification Channel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_description',
            field=models.TextField(
                help_text='Note: e.g Our top picks among new arrivals, best-sellers and limited-time deals.',
                max_length=255, verbose_name='Notification Description'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_name',
            field=models.CharField(db_index=True,
                                   help_text='Note: e.g Sales & Promotions or Personalized notifications',
                                   max_length=255, verbose_name='Notification Name'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason_label',
            field=models.TextField(db_index=True, help_text='Note: e.g Ordering experience, Technology related',
                                   max_length=255, verbose_name='Reason Label'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Delivery_Pickup', 'Delivery/Pickup')],
                                   db_index=True, help_text='Note: e.g Delivery/Pickup, Product', max_length=120,
                                   verbose_name='Reason Type'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='add_tip_post_delivery_days',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: This config will be used to control how many days after delivery the customer can increase tip. For example if the value is 7, then the option to increase tip or add tip post delivery should be available for 7 days. ',
                                              null=True, verbose_name='Add Tip Post Delivery Days'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='checkout_care_disclaimers',
            field=models.TextField(blank=True, help_text='Note: Provide the instruction to user on checkout screen.',
                                   null=True, verbose_name='Checkout Care Disclaimer'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='days_best_seller',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: This will be used to auto select products based on units sold of products in last X days. For example: if this field as a value of 7, then show those products which have sold the most in the last 7 days. ',
                                              null=True, verbose_name='Days Best Seller'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='days_new_item',
            field=models.PositiveIntegerField(blank=True,
                                              help_text="Note: This will be used to add the 'new' tag to the product. Example if this as a value of 7 means any new products added in the last 7 days will get the 'new tag'. ",
                                              null=True, verbose_name='Days New Item'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='delivery_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD',
                                                   help_text='Note: Delivery fee if minimum order amount is not met.',
                                                   max_digits=4, null=True, verbose_name='Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='filter_sold_out_from_our_picks',
            field=models.BooleanField(default=False,
                                      help_text="Note: 'Check' means filter out all out of stock items,  'Uncheck' means show all out of stock of item in put picks. ",
                                      verbose_name='Is Filter Sold Out From Our Picks?'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='fulfillment_remaining_spot_threshold',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: Number of reviews before they show up on the app to customers.',
                                              null=True, verbose_name='Fulfillment Remaining Spot Threshold'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='is_show_review',
            field=models.BooleanField(default=False,
                                      help_text='Note: Configure to show system wide reviews in the user facing application.',
                                      verbose_name='Is Show Review?'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='max_orders_for_review',
            field=models.PositiveIntegerField(blank=True,
                                              help_text="Note: This will be used on the 'my reviews' screen in my account to show hte no. of orders for review. ",
                                              null=True, verbose_name='Max Orders For Review'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='max_wholesale_threshold_to_sell',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: This value will be in percentage. This is the setting to calculate the max inventory from wholesale. Example take 90% wholesale_quantity and add it to to the 100% retail_quantity. ',
                                              null=True, verbose_name='Max Wholesale Threshold To Sell'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='minimum_reviews_count',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: Number of reviews before they show up on the app to customers.',
                                              null=True, verbose_name='Minimum Review Count'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='mobile_app_landing_screen_seq',
            field=models.CharField(blank=True,
                                   help_text='Note: Screen names: login, signup This will be used to decide which screen will the user see when he/she/other open the app the first time. ',
                                   max_length=30, null=True, verbose_name='Mobile App Landing Screen Sequence'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='order_share_code_expiry',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: Time after which the order share code will be expired.',
                                              null=True, verbose_name='Order Share Code Expiry'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='points_dollar_conversion',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: X points earned on each dollar for order placed. Ex: X = 1, all customers including super members will earn 1 points for each dollar for order placed. ',
                                              null=True, verbose_name='Points Dollar Conversion'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='points_expiry_days',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: Number of days after which the points will expire. 0 means points will never expire.',
                                              null=True, verbose_name='Points Expiry Days'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='quantity_remaining_threshold',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: Show quantities remaining if the remaining quantities is less than X units.',
                                              null=True, verbose_name='Quantity Remaining Threshold'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='referee_purchase_cutoff_days',
            field=models.PositiveIntegerField(blank=True,
                                              help_text='Note: Referee should make the purchase within X days or clicking on the link.',
                                              null=True, verbose_name='Referee Purchase Cutoff Days'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='referer_sharing_cutoff_days',
            field=models.PositiveIntegerField(blank=True, help_text='Note: After order is delivered or picked up.',
                                              null=True, verbose_name='Referer Sharing Cutoff Days.'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='return_window_time',
            field=models.PositiveIntegerField(blank=True,
                                              help_text="Note: System wide return window after which the returns won't be allowed.",
                                              null=True, verbose_name='Return Window Time'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='units_sold_threshold',
            field=models.PositiveIntegerField(blank=True,
                                              help_text="Note: This controls the minimum no. of units sold before showing the label '3k+ sold' on the app.",
                                              null=True, verbose_name='Units Sold Threshold'),
        ),
    ]
