# Generated by Django 3.2.13 on 2022-05-29 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0008_auto_20220529_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='county',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=120, verbose_name='County'),
            preserve_default=False,
        ),
    ]
