# Generated by Django 3.2.13 on 2022-05-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0009_zipcode_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lat',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='long',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
