# Generated by Django 3.2.13 on 2022-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0010_auto_20220529_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='city_rate',
            field=models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=9, verbose_name='City Tax Rate'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='combined_district_rate',
            field=models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=9, verbose_name='Combined District Tax Rate'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='county_rate',
            field=models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=9, verbose_name='County Tax Rate'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='special_rate',
            field=models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=9, verbose_name='Special Rate'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='state_rate',
            field=models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=9, verbose_name='State Tax Rate'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Status'),
        ),
    ]
