# Generated by Django 3.2.13 on 2022-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_management', '0012_legalterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalterm',
            name='effective_from',
            field=models.DateField(verbose_name='Effective From'),
        ),
        migrations.AlterField(
            model_name='legalterm',
            name='legal_file_name',
            field=models.CharField(max_length=255, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='legalterm',
            name='term_type',
            field=models.CharField(
                choices=[('Terms_Of_Service', 'Terms of service'), ('Privacy', 'Privacy'), ('Membership', 'Membership'),
                         ('Payment_Terms', 'Payment terms')], db_index=True, max_length=30, verbose_name='Terms Type'),
        ),
        migrations.AlterField(
            model_name='legalterm',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Version'),
        ),
    ]
